import type { Metadata } from "next";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";
import "./globals.scss";
import { Poppins } from "./fonts";
import { GlobalProvider } from './GlobalProvider'

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


interface RootLayoutProps {
	children: React.ReactNode;
	params: {
		locale: string;
	};
}

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<RootLayoutProps >) {
	return (
		<html lang={locale}>
			<body className={Poppins.className}>
				<Header />
   
<GlobalProvider>
{children}
</GlobalProvider>
				<Footer />
			</body>
		</html>
	);
}
