import type { Metadata } from "next";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";
import "./globals.scss";
import { Poppins } from "./fonts";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={Poppins.className}>
				<Header />

				{children}
				<Footer />
			</body>
		</html>
	);
}
